---
- name: Enable extra packages for RHEL OS family
  ansible.builtin.package:
    name: epel-release
  when: |
    ansible_distribution is defined
    and (ansible_distribution|lower == "almalinux"
         or ansible_distribution|lower == "redhat")
    and x2goclient_state != "absent"
  tags: x2goclient

- name: Make X2Go client {{ x2goclient_state }}
  ansible.builtin.package:
    name: x2goclient
    state: "{{ x2goclient_state }}"
    update_cache: true
  when: ansible_system|lower == "linux"
  tags: x2goclient

- name: Install X2Go client on Windows
  chocolatey.chocolatey.win_chocolatey:
    name: x2go
    state: "{{ x2goclient_state }}"
  when: ansible_system|lower == "win32nt"
  tags: win_chocolatey, x2goclient
